version: '3.8'

services:
  kong-db:
    image: postgres:13
    container_name: kong-db
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  kong-migrations:
    image: kong:3.4
    depends_on:
      kong-db:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
      KONG_PASSWORD: kongadmin
    command: kong migrations bootstrap
    restart: on-failure
    networks:
      - kong-net

  kong:
    image: kong:3.4
    container_name: kong
    depends_on:
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
      KONG_PASSWORD: kongadmin
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
    restart: on-failure
    networks:
      - kong-net

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    networks:
      - kong-net

  task-service:
    build:
      context: ./task-service
    container_name: task-service
    ports:
      - "3002:3002"
    networks:
      - kong-net

  project-service:
    build:
      context: ./project-service
    container_name: project-service
    ports:
      - "3003:3003"
    networks:
      - kong-net

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
